1. Huggingface Hub(Finetuning)
2. OpenAI SDK
3. Gemini SDK 

HF
Langchain

In [1]:
from sentence_transformers import SentenceTransformer

/Users/ruchisehgal/Documents/Study Material/Gen AI and Agentic AI/Embedding/newenv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
open_source_embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

In [3]:
text = "machine"
embedding =open_source_embedding_model.encode(text)
len(embedding)


384

In [4]:
embedding.shape

(384,)

In [5]:
sentence = "How to reduce heart disease risk?"
open_source_embedding_model.encode(sentence)

array([ 6.49378151e-02,  1.28513053e-01,  8.41138512e-03,  4.50836867e-02,
        6.74149534e-03,  2.71619279e-02, -7.06042051e-02,  2.64073759e-02,
       -3.79308388e-02, -2.38797534e-02, -6.41617272e-03, -1.86476170e-03,
        2.75909398e-02, -3.55664752e-02,  1.40230749e-02, -6.74081147e-02,
       -6.45455346e-02,  7.73962438e-02,  1.06312707e-02,  1.57817416e-02,
       -3.53638157e-02,  1.74661241e-02,  1.43505447e-03,  4.78440337e-02,
       -3.97442542e-02, -1.19458158e-02,  2.26343353e-03, -1.06840603e-01,
       -2.39676274e-02,  2.75909062e-02,  1.39234856e-01,  4.53187758e-03,
        7.27042854e-02,  1.19519467e-02, -7.98376501e-02,  5.52379079e-02,
        4.03933525e-02,  2.72679795e-02, -6.27351776e-02,  2.34903526e-02,
        8.01408943e-03, -4.28504422e-02, -5.53445844e-03,  6.84074219e-03,
        3.87948230e-02,  5.79556217e-03, -2.26256065e-02,  2.16249772e-03,
        5.31850308e-02,  3.31052719e-03, -8.02946016e-02,  4.53440333e-03,
       -8.07447657e-02, -

In [6]:
paragraph = """
Machine learning is a field of artificial intelligence that focuses on building systems 
that learn from data. It is widely used in applications like recommendation systems, 
image recognition, and natural language processing.
"""
open_source_embedding_model.encode(paragraph)

array([-2.78187096e-02, -6.40662154e-03,  3.68497893e-02,  2.21405155e-03,
        2.55084392e-02,  1.34023130e-02,  6.45563193e-03, -3.05501409e-02,
       -6.01915009e-02, -2.28518117e-02, -7.05489814e-02,  1.97643861e-02,
        5.54116927e-02, -3.38736363e-02, -9.74513125e-03,  4.72750440e-02,
       -1.58115271e-02, -1.64724384e-02, -6.00374974e-02, -7.00235888e-02,
        2.54246294e-02, -5.45076188e-03, -7.51982629e-02,  1.57804396e-02,
       -1.62698608e-02,  5.30246571e-02,  6.29331172e-02,  1.47747900e-02,
       -1.32339355e-02,  5.44602843e-03,  2.14248858e-02, -3.44793387e-02,
        1.16899498e-02,  4.35767211e-02, -4.42826524e-02,  5.05335033e-02,
       -2.66971737e-02,  5.36208367e-03,  7.96867814e-03, -1.89669747e-02,
       -6.25875145e-02, -7.47380555e-02,  6.55535934e-03, -6.77175261e-03,
        1.26145586e-01,  1.28760234e-01, -7.31317550e-02, -9.79881138e-02,
        8.16374319e-04,  1.73747428e-02, -1.05541244e-01,  1.18358694e-02,
       -1.23240715e-02,  

In [22]:
from dotenv import load_dotenv
import os

load_dotenv()  # loads from a .env file in the same directory

google_key = os.getenv("GOOGLE_API_KEY")
hf_token = os.getenv("HF_TOKEN")
openai_key = os.getenv("OPENAI_API_KEY")

In [24]:
import os

required_keys = ["GOOGLE_API_KEY", "HF_TOKEN", "OPENAI_API_KEY"]
missing = [k for k in required_keys if not os.getenv(k)]

if missing:
    print(f"Missing environment variables: {missing}")
else:
    for key in required_keys:
        os.environ[key] = os.getenv(key)

In [26]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
google_embeddings_model=GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")
embedding=google_embeddings_model.embed_query("Where is france?")


In [27]:
len(embedding)

3072

In [ ]:
from langchain_openai import OpenAIEmbeddings
openai_embeddings_model=OpenAIEmbeddings(model="text-embedding-3-large")
embedding = openai_embeddings_model.embed_query("Where is france?")


In [ ]:
from langchain_openai import OpenAIEmbeddings
openai_embeddings_model=OpenAIEmbeddings(model="text-embedding-3-small")
embedding = openai_embeddings_model.embed_query("Where is france?")


In [30]:
from transformers import CLIPModel, CLIPProcessor

In [31]:
from PIL import Image
image = Image.open("/Users/ruchisehgal/Documents/Study Material/Gen AI and Agentic AI/Embedding/SOTA-Transformer-Embedding-methods/Newpic.jpg")

In [32]:
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
inputs =processor(images=image, return_tensors="pt")

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


In [33]:
import torch
# Get embedding
with torch.no_grad():
    image_embedding = model.get_image_features(**inputs)

In [34]:
image_embedding

tensor([[ 6.5550e-02, -1.4679e-02, -2.6425e-01, -1.4959e-01,  1.5115e-01,
         -3.3140e-02,  3.2422e-01,  2.4146e-01,  3.2328e-01,  4.7851e-03,
          6.2896e-02,  2.0553e-02, -2.0689e-01, -6.1359e-01,  2.2687e-01,
         -4.2367e-01,  1.3753e-01,  2.0504e-01,  2.1087e-01,  5.8783e-01,
          2.7545e-02,  4.6963e-02,  3.3911e-01, -5.9081e-01, -4.4627e-01,
          3.7548e-01, -1.0083e-01,  1.0351e-01, -1.0770e-01, -3.6864e-01,
         -8.4931e-02,  3.9183e-01,  3.1928e-01,  4.3090e-01,  1.5070e-02,
          2.5865e-01,  3.3051e-01,  6.0965e-01, -6.9686e-02,  1.0652e+00,
          5.0737e-03,  2.3119e-01,  1.3939e-01, -1.5058e-01, -4.5663e-02,
          1.2056e-02, -1.2490e-01,  3.2374e-01,  5.1566e-01, -2.6179e-01,
          6.6229e-02,  2.9510e-01,  4.6050e-01,  1.3713e-01, -4.3362e-01,
          3.1516e-01,  3.8886e-01,  6.0461e-01,  1.1175e-01,  1.6680e-01,
          4.9654e-01, -1.9269e-01, -5.9642e-01, -2.2448e-01, -3.8962e-01,
         -4.0437e-01,  5.6273e-01,  9.

In [35]:
len(image_embedding[0])

512

Semantic Search (Similarity Search)
Dot Product
Cosine Sim
Eculidean Distance(L2)

In [38]:
import numpy as np
def dot_product(a, b):
    return np.dot(a, b)

In [36]:
import numpy as np
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [40]:
def euclidean_distance(a, b):
    a = np.array(a)
    b = np.array(b)
    return np.linalg.norm(a - b)

In [41]:
print("=== Cosine Similarity (Higher is better) ===")
print("Range: -1 to 1")

print("\n=== Dot Product (Higher is better) ===")
print("Range: -∞ to +∞ (depends on vector magnitude)")

print("\n=== Euclidean Distance (Lower is better) ===")
print("Range: 0 to +∞")

=== Cosine Similarity (Higher is better) ===
Range: -1 to 1

=== Dot Product (Higher is better) ===
Range: -∞ to +∞ (depends on vector magnitude)

=== Euclidean Distance (Lower is better) ===
Range: 0 to +∞


In [42]:
query = "How to reduce heart disease risk?"
documents = [
    "Eating fiber reduces heart risk.",
    "Fruits and vegetables lower cardiovascular disease chances.",
    "Buying a new car improves driving comfort.",
    "Regular exercise improves heart health."
]


In [43]:
query_embedding = google_embeddings_model.embed_query(query)

In [44]:
doc_embeddings = google_embeddings_model.embed_documents(documents)

In [45]:
len(doc_embeddings)

4

In [46]:
len(doc_embeddings[0])

3072

In [48]:
results=[]
for doc, doc_emb in zip(documents, doc_embeddings):
    results.append({
        "query": query,
        "document": doc,
        "cosine": cosine_similarity(query_embedding, doc_emb),
        "dot_product": dot_product(query_embedding, doc_emb),
        "euclidean": euclidean_distance(query_embedding, doc_emb)
    })

results

[{'query': 'How to reduce heart disease risk?',
  'document': 'Eating fiber reduces heart risk.',
  'cosine': 0.7395238839381586,
  'dot_product': 0.7395239069975954,
  'euclidean': 0.721770218537545},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Fruits and vegetables lower cardiovascular disease chances.',
  'cosine': 0.7132289221700364,
  'dot_product': 0.713228941549563,
  'euclidean': 0.7573256705301548},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Buying a new car improves driving comfort.',
  'cosine': 0.5761824193919591,
  'dot_product': 0.5761824550973114,
  'euclidean': 0.920671067071755},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Regular exercise improves heart health.',
  'cosine': 0.714166990937217,
  'dot_product': 0.7141670824821802,
  'euclidean': 0.7560860343930164}]

Keyword Search

In [49]:
from collections import Counter
query.lower().replace("?", "").split()



['how', 'to', 'reduce', 'heart', 'disease', 'risk']

In [50]:
query_words = query.lower().replace("?", "").split()

In [51]:
documents[0]

'Eating fiber reduces heart risk.'

In [52]:
doc_words = documents[0].lower().replace(".", "").split()

In [53]:
doc_words

['eating', 'fiber', 'reduces', 'heart', 'risk']

In [54]:
doc_count = Counter(doc_words)
doc_count

Counter({'eating': 1, 'fiber': 1, 'reduces': 1, 'heart': 1, 'risk': 1})

In [55]:
for word in query_words:
    print(f"{word}: {doc_count[word]}")

how: 0
to: 0
reduce: 0
heart: 1
disease: 0
risk: 1


In [57]:
score = sum(doc_count[word] for word in query_words) 
score

2

Score = number of matching words

In [58]:
def keyword_search(query, documents):
    query_words = query.lower().replace("?", "").split()
    results = []

    for doc in documents:
        doc_words = doc.lower().replace(".", "").split()
        doc_count = Counter(doc_words)

        score = sum(doc_count[word] for word in query_words) 
        results.append((doc, score))

    return sorted(results, key=lambda x: x[1], reverse=True)

In [60]:
keyword_results = keyword_search(query, documents)
keyword_results

[('Eating fiber reduces heart risk.', 2),
 ('Fruits and vegetables lower cardiovascular disease chances.', 1),
 ('Regular exercise improves heart health.', 1),
 ('Buying a new car improves driving comfort.', 0)]